### ISSUE TITLE
global name 'VERSION' is not defined

### ISSUE THREAD

**Issue by windmzx** [acopar/crow#39]
Hi, thanks to your contribute. I use it to factorization  my data matrix. When the process completed,I want to convert the result into csv file.But there is a error  as below:
Traceback (most recent call last):
  File "/home/crow/venv/bin/crow-conv", line 11, in <module>
    load_entry_point('crow==0.2', 'console_scripts', 'crow-conv')()
  File "/home/crow/venv/lib/python2.7/site-packages/crow-0.2-py2.7.egg/crow/convert/__main__.py", line 56, in main
    parser = argparse.ArgumentParser(version=VERSION, description='Crow converter')
NameError: global name 'VERSION' is not defined

**Comment by acopar** [comment]
Fixed in commit https://github.com/acopar/crow/commit/8c9b736372bfb274ed1708b0babde2556ca6937c.
